### ISSUE TITLE
Link code feature documentation to editors

### ISSUE THREAD

**Issue by rkoshak** [davidgraeff/paperui-ng#10]
Not only is syntax highlighting and checking really important, but this old Java programmer remembers how nice it was to be just one key combo away from the javadocs of the Class or method he was working with. I've seen this done in YAML based languages as well like Ansible playbooks in VSCode so it should theoretically be possible. 

It is a little harder in this case though because there is not just one source for the docs. There is javadocs of course for the Java classes we would use from inside the scripts. That should cover most of the OH specific stuff. But there are also Actions (e.g. mail) which would come from somewhere else maybe? And if one includes a third party library the docs for that library would be nice to have a key combo away.

**Comment by davidgraeff** [comment]
The vscode editor supports LSP which can provide autosuggestions and context information. I'm not sure if it can show API doc snippets as well, but I guess so. luckily openhab has to provide those and not the paper UI implementation.

**Comment by davidgraeff** [comment]
LSP should solve this, once the connection to a real openHAB instance works.
