### ISSUE TITLE
When scrolling through a long list of Items, Things, or Rules, keep place when switching views

### ISSUE THREAD

**Issue by rkoshak** [davidgraeff/paperui-ng#11]
If I scroll to the middle of a my Items in the gird view, for example, then switch to the list view, the first Item in the list should be the first visible Item from the grid view. It shouldn't jump around when I change views.

**Comment by davidgraeff** [comment]
Done. But we probably need key combos to switch between layouts, otherwise you have to scroll to the top to change it.

**Comment by rkoshak** [comment]
> But we probably need key combos to switch between layouts,

Or let those control elements persist on the screen as one scrolls.  I like the key combo idea though.
