### ISSUE TITLE
Change the sorting of Items, Thing, Rules in views

### ISSUE THREAD

**Issue by rkoshak** [davidgraeff/paperui-ng#12]
I don't know how much control there is over the Text views, but in the grid view and list view it would be helpful to be able to change the sorting order. Alphabetical is nice but last edit time would also be useful as all the Items/Things/Rules you are currently working on will be clustered at the top/bottom.

**Comment by davidgraeff** [comment]
Done.
This is now part of the the design study, but the actions have no click-and-play functionality yet.
