### ISSUE TITLE
Add VSCode extension support to editors

### ISSUE THREAD

**Issue by bkpsu** [davidgraeff/paperui-ng#14]
I appreciate the use of a VSCode control for the textual configuration (e.g. for familiarity with my current daily use), but will it allow the inclusion of the awesome openHAB extension? Or any other extensions/code helpers like VSCode does?

**Comment by davidgraeff** [comment]
The current editor is already 7mb in size. So no external add-ons. If you are talking about autosuggestions, that is possible.

There is a note right over the editor in the design study that is saying that no connection to openhab LSP could be established.
