### ISSUE TITLE
Bring in ZWave configuration ability

### ISSUE THREAD

**Issue by bkpsu** [davidgraeff/paperui-ng#15]
Would like to see Zwave-specific functionality built in/carried over from Habmin (mesh/device viewer, controller reset, network heal, etc…), so it’s a one-stop-shop for all my configuration (the integrated log viewer is already a great step towards that).

**Comment by davidgraeff** [comment]
Could you please elaborate on this idea. Please remember this is not a wish list, there is no payed development happening.

It is your duty to make this happen by first providing some screenshots on how you imagine that to look like. You can also edit the html directly and make a pull request.

**Comment by davidgraeff** [comment]
I have added a more generic solution
