### ISSUE TITLE
Make better use of side whitespace on wide monitors

### ISSUE THREAD

**Issue by bkpsu** [davidgraeff/paperui-ng#16]
As 5iver mentioned, there is a lot of wasted screen real estate on higher resolutions. I use an ultrawide monitor, at a resolution of 2560x1080, and would love to see the middle column extend to fill the screen (perhaps even add another column to the grid views, so more things/items/rules are visible on the screen at the same time).

**Comment by davidgraeff** [comment]
I have changed that already. The middle column is about 20% wider on large resolutions. That's the maximum before everything will look lost and out of place. If you open the old paper UI you should notice that as well.

I have chosen a 3-column design on purpose to avoid this. The content is centered and it just doesn't make sense for me to change this right now.

That doesn't mean it will not change in the future if someone comes up with an idea.
