### ISSUE TITLE
Add a button to disable filters

### ISSUE THREAD

**Issue by rkoshak** [davidgraeff/paperui-ng#19]
This is an approach I've seen in several software packages and I find it very useful. When using a program that allows complicated filters like this they often will add a little X button to the text box when there is a filter in effect that lets you remove all the filters at the click of a button.

![image](https://user-images.githubusercontent.com/6385096/51928726-cdc70080-23b3-11e9-91c2-84d05914af58.png)

It's a small thing but it really makes working with filters much easier for the user.

Here is an example from Calibre.

![image](https://user-images.githubusercontent.com/6385096/51928836-0bc42480-23b4-11e9-809b-13ba220a4cd8.png)

**Comment by davidgraeff** [comment]
Which browser are you using? Because chrome shows such a button on text box hover.

**Comment by rkoshak** [comment]
Chrome build 71.0.3578.98

**Comment by rkoshak** [comment]
I suppose I didn't hover over long enough. It seems to show up after about 10 seconds, though not consistently.

Not sure if there is an issue here.  I'll go ahead and close it.
