### ISSUE TITLE
Use another yaml->json library with pretty-print support

### ISSUE THREAD

**Issue by rkoshak** [davidgraeff/paperui-ng#2]
In the text view for Rules and I think also for Items some of the values entered are a full JSON structure.

![image](https://user-images.githubusercontent.com/6385096/51570911-af19b480-1e5d-11e9-9b6f-9c065678fab9.png)

Particularly for something that will be as involved as triggers and actions, we really need that JSON structure also presented in YAML format (or whatever the encoding of choice happens to become). The bulk of the complexity, and the bulk of manual edits in the text view will be to those two entries.

**Comment by davidgraeff** [comment]
Right click and chose "Format document". A NGRE rule that just acts on items, timed-tasks (timers) and other rules will not contain any javascript, so this mode will help the average user already.

**Comment by rkoshak** [comment]
> That is unfolded with the format document that I mentioned above.

I'm not certain I understand. Do you mean that, for example, we would get something like

```
triggers:
    id: '1'
    label: 'an item state changes'

and so on
```

instead of 

    triggers: [{id: '1', label: 'an item state changes', ... a bunch more JSON stuff

If so I'm good. If not, then I have real concerns about the YAML formatting because it really is insufficient. The bulk of any hand editing that one would have to do would still be in JSON. We may as well just present the whole Rule as JSON instead. The YAML really isn't adding anything.

**Comment by davidgraeff** [comment]
Try it out

**Comment by rkoshak** [comment]
It still looks like 

![image](https://user-images.githubusercontent.com/6385096/51612656-22173f80-1edf-11e9-9fe0-64daaf721e8e.png)


Am I doing something wrong?

**Comment by davidgraeff** [comment]
Done
