### ISSUE TITLE
Allow creation of Script Actions from "Add new rule" and use the Script Editor

### ISSUE THREAD

**Issue by rkoshak** [davidgraeff/paperui-ng#4]
Allow users to add a Script Action to wire up to a Rule created in the "Add new rule" view. When added, the user can select from one of the already existing Script Actions or create a new one. If they choose to create a new one, let them write the code using the "add new script" editor. Once saved or cancelled return to the "Add new rule" page of the Rule currently being worked on.

**Comment by davidgraeff** [comment]
I think I model it like the current Paper UI does it. By using a modal dialog with an embedded editor after clicking on the corresponding box.

**Comment by rkoshak** [comment]
As long as the editor has the same capabilities as the Script editor I think that would be OK. Though a major complaint I have with PaperUI's editor is the text box is too small (and doesn't resize properly but that's a bug and not by design).
