### ISSUE TITLE
Change the name of Timer to Schedule

### ISSUE THREAD

**Issue by rkoshak** [davidgraeff/paperui-ng#6]
"Schedule" is a better name for what this sub-module is doing.

**Comment by Hilbrand** [comment]
Should it not be the plural `Schedules`, similar to `Add-ons`, `Things`, `Items` and `Rules`? But English is not my first language. So I can't really tell.

**Comment by davidgraeff** [comment]
I think a schedule (singular) contains many scheduled items. So the singular is correct here, but not sure either.

**Comment by rkoshak** [comment]
I could see arguments either way, but at least in American English the plural sounds awkward. As with David's example, a singular schedule is made up of multiple events. Similarly, we wouldn't use "calendars" but just "calendar".

But it has been a very long time since I've taken any grammar lessons and their may be some rule or style guide that would say that the plural is more correct.

**Comment by davidgraeff** [comment]
Done
