### ISSUE TITLE
Include Astro Events in the Timer/Scheduler

### ISSUE THREAD

**Issue by rkoshak** [davidgraeff/paperui-ng#7]
If possible include the selection of Astro events (probably needs to be a generic Thing Channel really) so we can use the Scheduler around both static and astronomic date/times. This would make the scheduler very powerful and allow for the replacement of things like the Time of Day design pattern.

**Comment by davidgraeff** [comment]
> If possible include the selection of Astro events 

Is that actually needed? Because the astro binding could just provide a new "trigger" type and the scheduler is not required to be involved I guess.

**Comment by rkoshak** [comment]
I'm thinking of a Scheduler as a completely separate subsystem.

The interface between the Scheduler and Rules appears to be through an Item.

So I'm thinking of a scenario where I set up something like the Time of Day design pattern where we have a single Item that represents certain non-overlapping times of day. Some of the events are cron driven and some of the events are driven by Astro. Having access to these all within one GUI will allow:

- replacement of the need for a Rule to drive this sort of scheduling
- opportunity to provide a calendar view of the scheduled events (which I can't remember if there was a view of scheduled events)
- provides a unified place for all a user's scheduling type activities

It may not make sense or be too much effort for the benefit, but my thought is if this is going to be a Scheduler, it should let me manage all scheduling related stuff.

**Comment by davidgraeff** [comment]
You misunderstood the UI and I need to accommodate for that. Maybe be inline help texts that explain the difference.

Initially I did not plan to trigger items at all.
A timed-task will just trigger when it times out. That can be used in rules as the trigger event.

I have added the item part only to make it easier for people to migrate away from the OH1 expire binding.

**Comment by davidgraeff** [comment]
> opportunity to provide a calendar view of the scheduled events (which I can't remember if there was a view of scheduled events)

A calender view is a good idea. We could have list/grid/textual/calender view. The calender view would only be a projection of real timed-tasks into a narrow time space, but it would look good.

**Comment by davidgraeff** [comment]
> provides a unified place for all a user's scheduling type activities

It is. Bindings are already today creating timed-tasks via the main openhab scheduler, also the astro binding. I plan a switch on the left menu to show those timed-tasks as well, so the user will see them in a calender overview. 

I really don't see the need yet to integrate that here. The entire astro logic part would be required in the browser and that really belongs into a binding. We should more think about how to change those date/time related bindings to show up here in the scheduler list with a good name etc. Those timed-tasks do not have a label / description yet in bindings.

**Comment by rkoshak** [comment]
> A calender view is a good idea. We could have list/grid/textual/calender view. The calender view would only be a projection of real timed-tasks into a narrow time space, but it would look good.

Even if it is just a week that should be sufficient. I suspect a lot of people will be scheduling their HVAC systems from this subsystem so the ability to see and modify events across multiple days would be helpful and useful.

> A calender view is a good idea. We could have list/grid/textual/calender view. The calender view would only be a projection of real timed-tasks into a narrow time space, but it would look good.

👍 

> We should more think about how to change those date/time related bindings to show up here in the scheduler list with a good name etc. Those timed-tasks do not have a label / description yet in bindings.

I figured it would be really involved to make it work. This is certainly not a show stopper for the initial version by any means. It's just an idea that occurred to me as I reviewed the study.

**Comment by davidgraeff** [comment]
For now I'm closing this :)
