### ISSUE TITLE
Let's drop PaperUI from the Name

### ISSUE THREAD

**Issue by rkoshak** [davidgraeff/paperui-ng#9]
I think it would be good to make a clean break from PaperUI and come up with a new name. This new UI is completely new and it deserves it's own name.

**Comment by Simsal** [comment]
I want to add that I would also want to drop the ng from the name, as ng is mostly used as short for angular (2+).
I know that you meant it as next generation, but as I saw the 'ng' I already wanted to offer my help in programming as I my front end stuff mostly in Angular, so I were a little bit disappointed to see vue ;)

**Comment by davidgraeff** [comment]
But the angular team has used "ng" also in the sense of "new generation" didn't they? (Like new-generation-repeat in short "ng-repeat"). There is no better suffix available atm, maybe you come up with sth.
